name = "gomoku-llm"
main = "./src/worker/index.ts"
compatibility_date = "2024-03-29"

# [build]
# command = "npm run build:worker"

[assets]
directory = "./dist/client"
binding = "ASSETS"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[env.staging.observability]
enabled = true
head_sampling_rate = 1 # optional

[observability.logs]
enabled = true

[vars]
# Public environment variables can be set here
ENVIRONMENT = "production"

# Secret variables should be set using wrangler secret put command
# wrangler secret put GOMOKU_AI_API_KEY

# 新的路由格式
routes = [
  "/",
  "/api/*"
]